# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: erickveil.net
email: erick@erickveil.net
description: > # this means to ignore newlines until "baseurl:"
    Sharing a little bit of what I've learned so far with the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://erickveil.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
#markdown: kramdown
markdown: redcarpet


highlighter: rouge

timezone: America/Los_Angeles
